#pragma once
#include "GameObject.h"

#define FPP_BBOX_WIDTH 16
#define FPP_BBOX_HEIGHT 33

#define ID_ANI_FPP_LEFT_TOP 50002
#define ID_ANI_FPP_LEFT_BOTTOM 50003
#define ID_ANI_FPP_LEFT_TOP_SHOOT 50004
#define ID_ANI_FPP_LEFT_BOTTOM_SHOOT 50005
#define ID_ANI_FPP_RIGHT_TOP 50006
#define ID_ANI_FPP_RIGHT_BOTTOM 50007
#define ID_ANI_FPP_RIGHT_TOP_SHOOT 50008
#define ID_ANI_FPP_RIGHT_BOTTOM_SHOOT 50009

#define FPP_SPEED 0.02f

#define FPP_BIG 1
#define FPP_SMALL 2
class FirePiranhaPlant
{
};

